name: deploy to elastic beanstalks
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploytoelb:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3

      - name: setup the java and maven environment
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: build artifact wit maven
        run: mvn package

      - name: analyze with sonarclouds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tmelong91_Xashy-webapp-EBST

      - name: publish to github packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Deploy to s3
        run: aws s3 cp target/*war s3://xashy-web-app

      - name: Create ELB app version for artifact
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name web-app \
          --source-bundle S3Bucket="xashy-web-app",S3Key="xashy-webapp.war" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: update environment with application version
        run: aws elasticbeanstalk update-environment --environment-name Web-app-env --version-label "ver-${{ github.sha }}"
